"use client";

import Link from "next/link";
import { Bell, BellRing, Check, CheckCircle2, ChevronRight, Mail, Radio, RefreshCw, ShieldAlert, Smartphone, Trash2, Zap } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import "../../developer.css";
import "./notifications.css";

type NotificationItem = { id: string; eventType: string; severity: "info" | "warning" | "critical"; title: string; body: string; readAt: string | null; createdAt: string; };
type Rule = { id: string; event_type: string; enabled: boolean; severity: "info" | "warning" | "critical"; channels: string[]; cooldown_seconds: number; };
type Preferences = { browser_enabled: boolean; email_enabled: boolean; email_address: string | null; minimum_severity: "info" | "warning" | "critical" };

const labels: Record<string,string> = { "whatsapp.connection": "WhatsApp connection", "broadcast.failure": "Broadcast failures", "worker.failure": "Worker failures", "webhook.failure": "Webhook failures" };

export default function NotificationsPage() {
  const [items,setItems]=useState<NotificationItem[]>([]),[unread,setUnread]=useState(0),[rules,setRules]=useState<Rule[]>([]),[prefs,setPrefs]=useState<Preferences>({browser_enabled:true,email_enabled:false,email_address:null,minimum_severity:"warning"}),[pushReady,setPushReady]=useState(false),[subscribed,setSubscribed]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");

  const load = useCallback(async()=>{setLoading(true);setError("");try{const [n,r,p,c]=await Promise.all([fetch("/api/v1/notifications",{cache:"no-store"}),fetch("/api/v1/notifications/rules",{cache:"no-store"}),fetch("/api/v1/notifications/preferences",{cache:"no-store"}),fetch("/api/v1/notifications/config",{cache:"no-store"})]);const [nb,rb,pb,cb]=await Promise.all([n.json(),r.json(),p.json(),c.json()]);if(!n.ok)throw new Error(nb?.error?.message||"Unable to load notifications.");setItems(nb.data?.notifications||[]);setUnread(nb.data?.unread||0);if(rb.ok)setRules(rb.data?.rules||[]);if(pb.ok)setPrefs(pb.data);if(cb.ok)setPushReady(Boolean(cb.data?.browserPushConfigured));const s=await fetch("/api/v1/notifications/push",{cache:"no-store"});const sb=await s.json();if(s.ok)setSubscribed(Boolean(sb.data?.subscribed));}catch(e){setError(e instanceof Error?e.message:"Unable to load notification center.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const unreadItems=useMemo(()=>items.filter(x=>!x.readAt),[items]);
  async function markRead(ids:string[]){if(!ids.length)return;setBusy(true);try{const r=await fetch("/api/v1/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});if(!r.ok)throw new Error("Could not mark notifications as read.");await load()}catch(e){setError(e instanceof Error?e.message:"Could not update notifications.")}finally{setBusy(false)}}
  async function clearRead(){setBusy(true);try{const r=await fetch("/api/v1/notifications",{method:"DELETE"});if(!r.ok)throw new Error("Could not clear notifications.");await load()}catch(e){setError(e instanceof Error?e.message:"Could not clear notifications.")}finally{setBusy(false)}}
  async function savePrefs(next:Partial<Preferences>){setBusy(true);setError("");try{const r=await fetch("/api/v1/notifications/preferences",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({browserEnabled:next.browser_enabled,emailEnabled:next.email_enabled,emailAddress:next.email_address,minimumSeverity:next.minimum_severity})});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Unable to save notification preferences.");setPrefs(b.data);setMessage("Preferences saved");window.setTimeout(()=>setMessage(""),1800)}catch(e){setError(e instanceof Error?e.message:"Unable to save notification preferences.")}finally{setBusy(false)}}
  async function enablePush(){setBusy(true);setError("");try{if(!pushReady)throw new Error("Browser push is not configured on this deployment. Add the VAPID variables first.");if(!("serviceWorker" in navigator)||!("PushManager" in window))throw new Error("This browser does not support push notifications.");const cfg=await (await fetch("/api/v1/notifications/config")).json();const registration=await navigator.serviceWorker.register("/notifications-sw.js");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Browser notification permission was not granted.");const current=await registration.pushManager.getSubscription();const push=current||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(cfg.data.vapidPublicKey)});const r=await fetch("/api/v1/notifications/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(push.toJSON())});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Unable to enable browser push.");setSubscribed(true);setPrefs(x=>({...x,browser_enabled:true}));setMessage("Browser push is live");window.setTimeout(()=>setMessage(""),1800)}catch(e){setError(e instanceof Error?e.message:"Unable to enable browser push.")}finally{setBusy(false)}}
  async function disablePush(){setBusy(true);try{const r=await fetch("/api/v1/notifications/push",{method:"DELETE"});if(!r.ok)throw new Error("Unable to disable browser push.");if("serviceWorker" in navigator){const reg=await navigator.serviceWorker.getRegistration("/notifications-sw.js");const sub=await reg?.pushManager.getSubscription();await sub?.unsubscribe()}setSubscribed(false);setMessage("Browser push disabled")}catch(e){setError(e instanceof Error?e.message:"Unable to disable browser push.")}finally{setBusy(false)}}
  async function test(){setBusy(true);try{const r=await fetch("/api/v1/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({test:true})});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Unable to create test notification.");setMessage("Test notification queued");window.setTimeout(()=>{void load()},900)}catch(e){setError(e instanceof Error?e.message:"Unable to create test notification.")}finally{setBusy(false)}}
  async function saveRule(rule:Rule){setBusy(true);try{const r=await fetch("/api/v1/notifications/rules",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventType:rule.event_type,enabled:rule.enabled,severity:rule.severity,channels:rule.channels,cooldownSeconds:rule.cooldown_seconds})});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Unable to save rule.");setRules(x=>x.map(item=>item.event_type===rule.event_type?b.data:item));setMessage("Rule updated");window.setTimeout(()=>setMessage(""),1400)}catch(e){setError(e instanceof Error?e.message:"Unable to save rule.")}finally{setBusy(false)}}

  return <main className="developer-shell notification-shell"><div className="developer-orb developer-orb-one"/><div className="developer-orb developer-orb-two"/><section className="developer-header notification-hero"><div><div className="developer-kicker"><BellRing size={13}/> LaaWa Operations</div><h1>Notification Center</h1><p>Catch connection failures, campaign delivery problems, worker crashes and webhook incidents before they become silent failures.</p></div><div className="notification-live"><span/><div><strong>{unread}</strong><small>unread alerts</small></div></div></section><div className="developer-quicknav"><Link href="/developer/docs">API Docs</Link><Link href="/developer/engines">Engine Control Center</Link><Link href="/developer/sdk">SDKs</Link><Link href="/developer/n8n">n8n</Link><Link href="/developer/integrations">Integrations</Link><Link className="active" href="/developer/notifications"><Bell size={14}/> Notifications</Link></div>{error&&<div className="developer-error">{error}</div>}{message&&<div className="notification-toast"><CheckCircle2 size={16}/>{message}</div>}
    <section className="notification-overview"><article className="notification-stat"><span><Zap size={17}/></span><strong>{unread}</strong><small>Needs attention</small></article><article className="notification-stat"><span><Radio size={17}/></span><strong>{rules.filter(r=>r.enabled).length}</strong><small>Active rules</small></article><article className="notification-stat"><span><Smartphone size={17}/></span><strong>{subscribed?"LIVE":"OFF"}</strong><small>Browser push</small></article><article className="notification-stat"><span><Mail size={17}/></span><strong>{prefs.email_enabled?"LIVE":"OFF"}</strong><small>Email alerts</small></article></section>
    <section className="notification-grid"><article className="developer-card notification-feed"><div className="notification-card-head"><div><div className="developer-card-title"><span className="developer-icon"><Bell size={18}/></span><div><h2>Live alert feed</h2><p>Newest operational events first.</p></div></div></div><div className="notification-actions"><button onClick={()=>void load()} disabled={loading||busy} title="Refresh"><RefreshCw size={15}/></button><button onClick={()=>void markRead(unreadItems.map(x=>x.id))} disabled={busy||!unreadItems.length}>Mark all read</button><button onClick={()=>void clearRead()} disabled={busy}><Trash2 size={15}/></button></div></div>{loading?<div className="notification-empty shimmer">Synchronizing your operations feed…</div>:!items.length?<div className="notification-empty"><CheckCircle2 size={30}/><strong>All clear</strong><span>No operational notifications yet.</span></div>:<div className="notification-list">{items.map(item=><div key={item.id} className={`notification-item ${item.severity} ${item.readAt?"read":"unread"}`}><div className="notification-severity"><ShieldAlert size={17}/></div><div className="notification-copy"><div><strong>{item.title}</strong><time>{new Date(item.createdAt).toLocaleString()}</time></div><p>{item.body}</p><span>{labels[item.eventType]||item.eventType}</span></div>{!item.readAt&&<button className="notification-read" onClick={()=>void markRead([item.id])} disabled={busy}><Check size={15}/></button>}</div>)}</div>}</article>
      <aside className="notification-side"><article className="developer-card notification-settings"><div className="developer-card-title"><span className="developer-icon"><Smartphone size={18}/></span><div><h2>Delivery channels</h2><p>Choose where critical signals land.</p></div></div><div className="channel-row"><div><strong>Browser push</strong><small>{subscribed?"This browser is subscribed":"Instant desktop alerts"}</small></div><button className={subscribed?"toggle on":"toggle"} onClick={()=>void (subscribed?disablePush():enablePush())} disabled={busy||!pushReady}><span/></button></div><div className="channel-row"><div><strong>Email alerts</strong><small>{prefs.email_address||"SMTP delivery"}</small></div><button className={prefs.email_enabled?"toggle on":"toggle"} onClick={()=>void savePrefs({email_enabled:!prefs.email_enabled})} disabled={busy}><span/></button></div>{prefs.email_enabled&&<input className="notification-input" value={prefs.email_address||""} onChange={e=>setPrefs(x=>({...x,email_address:e.target.value}))} onBlur={()=>void savePrefs({email_address:prefs.email_address})} placeholder="alerts@example.com" type="email"/>}<label className="notification-select">Minimum severity<select value={prefs.minimum_severity} onChange={e=>void savePrefs({minimum_severity:e.target.value as Preferences["minimum_severity"]})}><option value="info">Info and above</option><option value="warning">Warning and above</option><option value="critical">Critical only</option></select></label><button className="developer-primary" onClick={()=>void test()} disabled={busy}><BellRing size={16}/> Send test alert</button><p className="notification-hint">{pushReady?"VAPID push is configured.":"Browser push needs VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY and VAPID_SUBJECT."}</p></article>
        <article className="developer-card notification-rules"><div className="developer-card-title"><span className="developer-icon"><ShieldAlert size={18}/></span><div><h2>Alert rules</h2><p>Control severity, channels and noise.</p></div></div>{rules.map(rule=><div className="rule" key={rule.event_type}><div className="rule-head"><strong>{labels[rule.event_type]||rule.event_type}</strong><button className={rule.enabled?"toggle on":"toggle"} onClick={()=>void saveRule({...rule,enabled:!rule.enabled})} disabled={busy}><span/></button></div><div className="rule-controls"><select value={rule.severity} onChange={e=>void saveRule({...rule,severity:e.target.value as Rule["severity"]})} disabled={busy}><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select><div className="rule-channels">{["browser","email"].map(channel=><button key={channel} className={rule.channels.includes(channel)?"channel-chip active":"channel-chip"} onClick={()=>void saveRule({...rule,channels:rule.channels.includes(channel)?rule.channels.filter(x=>x!==channel):[...rule.channels,channel]})} disabled={busy}>{channel}</button>)}</div></div></div>)}</article></aside></section></main>;
}

function urlBase64ToUint8Array(value:string){const padding="=".repeat((4-value.length%4)%4);const base64=(value+padding).replace(/-/g,"+").replace(/_/g,"/");const raw=window.atob(base64);return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)));}
