"use client";

import Link from "next/link";
import { Activity, AlertTriangle, BarChart3, Bell, CheckCircle2, Clock3, Gauge, Layers3, Radio, RefreshCw, Server, ShieldCheck, Sparkles, Workflow, Zap } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import "../../developer.css";
import "./observability.css";

type Snapshot={generatedAt:string;accounts:{total:number;connected:number;reconnecting:number;error:number};messages:{total:number;inbound:number;outbound:number;failed:number;last24h:number};conversations:{total:number;open:number;unread:number};broadcasts:{total:number;running:number;failed:number;completed:number;recipientsFailed:number};jobs:{queued:number;running:number;failed:number;completed:number};webhooks:{enabled:number;pending:number;failed:number;delivered:number};notifications:{unread:number;pendingDelivery:number;deliveryErrors:number};automations:{enabledRules:number;failedRuns24h:number}};
const initial:Snapshot={generatedAt:"",accounts:{total:0,connected:0,reconnecting:0,error:0},messages:{total:0,inbound:0,outbound:0,failed:0,last24h:0},conversations:{total:0,open:0,unread:0},broadcasts:{total:0,running:0,failed:0,completed:0,recipientsFailed:0},jobs:{queued:0,running:0,failed:0,completed:0},webhooks:{enabled:0,pending:0,failed:0,delivered:0},notifications:{unread:0,pendingDelivery:0,deliveryErrors:0},automations:{enabledRules:0,failedRuns24h:0}};
function fmt(n:number){return new Intl.NumberFormat("en-IN",{notation:n>9999?"compact":"standard",maximumFractionDigits:1}).format(n)}
function Health({value,good=true}:{value:number;good?:boolean}){return <span className={value>0&&!good?"metric-health bad":"metric-health good"}><i/>{value>0&&!good?`${fmt(value)} issue${value===1?"":"s"}`:"Healthy"}</span>}
export default function ObservabilityPage(){
 const [data,setData]=useState<Snapshot>(initial),[loading,setLoading]=useState(true),[error,setError]=useState(""),[auto,setAuto]=useState(true),[last,setLast]=useState<Date|null>(null);
 const load=useCallback(async()=>{try{setError("");const r=await fetch("/api/v1/metrics/snapshot",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Unable to load metrics.");setData(b.data);setLast(new Date())}catch(e){setError(e instanceof Error?e.message:"Metrics unavailable")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();if(!auto)return;const id=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(id)},[load,auto]);
 const health=useMemo(()=>data.accounts.error+data.messages.failed+data.broadcasts.failed+data.jobs.failed+data.webhooks.failed+data.notifications.deliveryErrors+data.automations.failedRuns24h,[data]);
 return <main className="developer-shell observability-shell"><div className="developer-orb developer-orb-one"/><div className="developer-orb developer-orb-two"/><section className="developer-header obs-hero"><div><div className="developer-kicker"><Activity size={13}/> LaaWa Operations</div><h1>Observability</h1><p>One operational surface for WhatsApp health, message flow, automation, delivery, jobs and alerts.</p></div><div className="obs-status"><span className={health?"danger":"live"}/><div><strong>{health?`${fmt(health)} signals need attention`:"All systems nominal"}</strong><small>{last?`Updated ${last.toLocaleTimeString()}`:"Synchronizing…"}</small></div></div></section><div className="developer-quicknav"><Link href="/developer/docs">API Docs</Link><Link href="/developer/engines"><Layers3 size={14}/> Engines</Link><Link href="/developer/sdk">SDKs</Link><Link href="/developer/n8n"><Workflow size={14}/> n8n</Link><Link href="/developer/integrations">Integrations</Link><Link href="/developer/notifications"><Bell size={14}/> Notifications</Link><Link className="active" href="/developer/observability"><Activity size={14}/> Observability</Link></div>{error&&<div className="developer-error">{error}</div>}
 <section className="obs-toolbar"><div><div className="obs-dotline"><span/>Operational telemetry</div><small>Prometheus-compatible metrics are available at <code>/api/v1/metrics</code>.</small></div><div className="obs-toolbar-actions"><button className={auto?"obs-toggle active":"obs-toggle"} onClick={()=>setAuto(x=>!x)}><Clock3 size={14}/>{auto?"Auto refresh 15s":"Auto refresh off"}</button><button onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?"spin":""} size={14}/> Refresh</button></div></section>
 <section className="obs-primary-grid"><article className="obs-big-card"><div className="obs-card-head"><div><span className="obs-icon"><Gauge size={18}/></span><div><h2>System pulse</h2><p>Current workspace operating state.</p></div></div><Health value={health} good={!health}/></div><div className="pulse-ring"><div><strong>{loading?"—":health?fmt(health):"OK"}</strong><small>{health?"attention signals":"nominal"}</small></div></div><div className="pulse-foot"><span><Server size={14}/> {fmt(data.accounts.connected)} / {fmt(data.accounts.total)} accounts connected</span><span><Zap size={14}/> {fmt(data.messages.last24h)} messages / 24h</span></div></article><article className="obs-card"><div className="obs-card-head"><div><span className="obs-icon"><Radio size={18}/></span><div><h2>WhatsApp engines</h2><p>Connection posture</p></div></div></div><div className="obs-metric-row"><strong>{fmt(data.accounts.connected)}</strong><span>connected</span><b>{data.accounts.total?Math.round(data.accounts.connected/data.accounts.total*100):0}%</b></div><div className="obs-progress"><span style={{width:`${data.accounts.total?Math.min(100,data.accounts.connected/data.accounts.total*100):0}%`}}/></div><div className="obs-mini-grid"><div><strong>{fmt(data.accounts.reconnecting)}</strong><small>reconnecting</small></div><div><strong>{fmt(data.accounts.error)}</strong><small>errors</small></div></div></article></section>
 <section className="obs-card-grid"><Metric title="Messages" icon={<BarChart3 size={17}/>} value={data.messages.total} lines={[["Inbound",data.messages.inbound],["Outbound",data.messages.outbound],["Last 24h",data.messages.last24h],["Failed",data.messages.failed]]} bad={data.messages.failed}/><Metric title="Conversations" icon={<Radio size={17}/>} value={data.conversations.total} lines={[["Open",data.conversations.open],["Unread",data.conversations.unread]]}/><Metric title="Broadcasts" icon={<Zap size={17}/>} value={data.broadcasts.total} lines={[["Running",data.broadcasts.running],["Completed",data.broadcasts.completed],["Failed",data.broadcasts.failed],["Recipient failures",data.broadcasts.recipientsFailed]]} bad={data.broadcasts.failed+data.broadcasts.recipientsFailed}/><Metric title="Durable jobs" icon={<Activity size={17}/>} value={data.jobs.running+data.jobs.queued} lines={[["Running",data.jobs.running],["Queued",data.jobs.queued],["Completed",data.jobs.completed],["Failed",data.jobs.failed]]} bad={data.jobs.failed}/><Metric title="Webhooks" icon={<Workflow size={17}/>} value={data.webhooks.enabled} lines={[["Delivered",data.webhooks.delivered],["Pending",data.webhooks.pending],["Failed",data.webhooks.failed]]} bad={data.webhooks.failed}/><Metric title="Notifications" icon={<Bell size={17}/>} value={data.notifications.unread} lines={[["Unread",data.notifications.unread],["Pending delivery",data.notifications.pendingDelivery],["Delivery errors",data.notifications.deliveryErrors]]} bad={data.notifications.deliveryErrors}/><Metric title="Automations" icon={<Sparkles size={17}/>} value={data.automations.enabledRules} lines={[["Enabled rules",data.automations.enabledRules],["Failed / 24h",data.automations.failedRuns24h]]} bad={data.automations.failedRuns24h}/><article className="obs-card obs-security"><div className="obs-card-title"><span className="obs-icon"><ShieldCheck size={17}/></span><div><h2>Telemetry security</h2><p>Workspace-scoped and API-authenticated.</p></div></div><div className="security-list"><span><CheckCircle2 size={15}/> No plaintext secrets</span><span><CheckCircle2 size={15}/> No cross-workspace aggregation</span><span><CheckCircle2 size={15}/> Cache disabled for live metrics</span><span><CheckCircle2 size={15}/> Standard Prometheus text format</span></div></article></section>
 <section className="obs-footer-card"><div><div className="developer-kicker"><AlertTriangle size={13}/> Production telemetry</div><h2>Built for your own infrastructure.</h2><p>The dashboard is served by Next.js and remains compatible with Netlify/Vercel. External Prometheus scraping uses the authenticated v1 metrics endpoint; no always-on metrics process is required.</p></div><Link href="/developer/docs">Open API docs <span>→</span></Link></section>
 </main>;
}
function Metric({title,icon,value,lines,bad=0}:{title:string;icon:React.ReactNode;value:number;lines:[string,number][];bad?:number}){return <article className="obs-card metric-card"><div className="obs-card-title"><span className="obs-icon">{icon}</span><div><h2>{title}</h2><p>Live workspace gauge</p></div></div><strong className="metric-value">{fmt(value)}</strong><div className="metric-lines">{lines.map(([label,num])=><div key={label}><span>{label}</span><b className={bad&&label.toLowerCase().includes("fail")?"bad-number":""}>{fmt(num)}</b></div>)}</div></article>}
