"use client";

import { useEffect, useMemo, useState } from "react";
import { ContactRound, Search, Plus, Tag, Save, X, RefreshCw } from "lucide-react";

type TagRow={id:string;name:string;count:number};
type Contact={id:string;name:string|null;push_name:string|null;phone:string|null;email:string|null;notes:string|null;account_name:string|null;tags:TagRow[]};

export default function ContactsHub(){
 const [contacts,setContacts]=useState<Contact[]>([]),[tags,setTags]=useState<TagRow[]>([]),[search,setSearch]=useState(""),[tagId,setTagId]=useState(""),[selected,setSelected]=useState<Contact|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const [draft,setDraft]=useState({name:"",phone:"",email:"",notes:""});
 async function load(){setLoading(true);try{const q=new URLSearchParams();if(search.trim())q.set("search",search.trim());if(tagId)q.set("tagId",tagId);const r=await fetch(`/api/contacts?${q}`,{cache:"no-store"});const d=await r.json();if(r.ok){setContacts(d.contacts||[]);setTags(d.tags||[])}else setMessage(d.error||"Could not load contacts.")}catch{setMessage("Could not reach the contact service.")}finally{setLoading(false)}}
 useEffect(()=>{const t=window.setTimeout(load,180);return()=>window.clearTimeout(t)},[search,tagId]);
 function edit(c:Contact){setSelected(c);setDraft({name:c.name||c.push_name||"",phone:c.phone||"",email:c.email||"",notes:c.notes||""});setMessage("")}
 async function save(){if(!selected)return;setSaving(true);setMessage("");try{const r=await fetch("/api/contacts",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,...draft})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed");await load();setSelected(null);setMessage("Contact saved.")}catch(e){setMessage(e instanceof Error?e.message:"Save failed.")}finally{setSaving(false)}}
 const visibleCount=useMemo(()=>contacts.length,[contacts]);
 return <section className="contacts-hub">
  <div className="contacts-hero glass"><div className="contacts-orbit"><span/><span/><span/><ContactRound size={34}/></div><div><div className="eyebrow">CONTACT INTELLIGENCE</div><h2>Customer 360</h2><p className="muted">One live profile layer for every WhatsApp relationship.</p></div><div className="contacts-stat"><strong>{visibleCount}</strong><span>visible contacts</span></div></div>
  <div className="contacts-toolbar glass"><div className="searchbox"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, phone or email…"/></div><select value={tagId} onChange={e=>setTagId(e.target.value)}><option value="">All segments</option>{tags.map(t=><option key={t.id} value={t.id}>{t.name} · {t.count}</option>)}</select><button className="icon-button" onClick={load} title="Refresh"><RefreshCw size={17}/></button></div>
  {message&&<div className="success">{message}</div>}
  <div className="contacts-layout"><aside className="contacts-tags glass"><div className="panel-head"><div><div className="eyebrow">SEGMENTS</div><h3>Tags</h3></div><Tag size={17}/></div>{tags.length===0?<div className="empty"><strong>No tags yet</strong><span>Tags created by campaigns and automations will appear here.</span></div>:tags.map(t=><button key={t.id} className={tagId===t.id?"tag-filter active":"tag-filter"} onClick={()=>setTagId(tagId===t.id?"":t.id)}><span>{t.name}</span><b>{t.count}</b></button>)}</aside>
   <div className="contacts-list glass"><div className="panel-head"><div><div className="eyebrow">LIVE DIRECTORY</div><h3>Contacts</h3></div><span className="small muted">{loading?"Syncing…":`${contacts.length} loaded`}</span></div>{loading?<div className="empty"><strong>Loading contacts…</strong></div>:contacts.length===0?<div className="empty"><strong>No matching contacts</strong><span>Connect WhatsApp or create contacts through your workspace flows.</span></div>:<div className="contact-grid">{contacts.map(c=><button className="contact-card" key={c.id} onClick={()=>edit(c)}><div className="contact-avatar">{(c.name||c.push_name||"?").slice(0,1).toUpperCase()}</div><div className="contact-main"><strong>{c.name||c.push_name||"Unnamed contact"}</strong><span>{c.phone||c.email||"No contact detail"}</span><div className="contact-tags">{c.tags.slice(0,3).map(t=><em key={t.id}>{t.name}</em>)}</div></div><span className="small muted">{c.account_name||"Unassigned"}</span></button>)}</div>}</div>
  </div>
  {selected&&<div className="contact-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="contact-editor glass"><div className="panel-head"><div><div className="eyebrow">PROFILE</div><h3>Edit contact</h3></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="editor-fields"><label>Name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Phone<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Email<input value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Notes<textarea rows={5} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div><button className="primary" onClick={save} disabled={saving}><Save size={16}/>{saving?"Saving…":"Save profile"}</button></div></div>}
 </section>
}
