"use client";

import { useEffect, useMemo, useState } from "react";
import { BrainCircuit, RefreshCw, MessageCircle, Clock3, AlertTriangle, Search, Sparkles, X, Copy, Check, type LucideIcon } from "lucide-react";

type Conversation={id:string;name:string|null;phone:string|null;title:string|null;unread_count:number;message_count:number;inbound:number;outbound:number;failed:number;sentiment:"positive"|"negative"|"neutral";responseMinutes:number|null;preview:string};
type Data={configured:boolean;summary:{total:number;open:number;unread:number;inbound:number;outbound:number;avgResponseMinutes:number|null};conversations:Conversation[]};

const EMPTY_SUMMARY: Data["summary"] = { total: 0, open: 0, unread: 0, inbound: 0, outbound: 0, avgResponseMinutes: null };

export default function IntelligenceHub(){
 const [data,setData]=useState<Data|null>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [selected,setSelected]=useState<Conversation|null>(null),[assist,setAssist]=useState(""),[assistLoading,setAssistLoading]=useState(false),[assistError,setAssistError]=useState(""),[copied,setCopied]=useState(false);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/intelligence",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load intelligence");setData({configured:Boolean(d.configured),summary:{...EMPTY_SUMMARY,...(d.summary||{})},conversations:Array.isArray(d.conversations)?d.conversations:[]})}catch(e){setError(e instanceof Error?e.message:"Could not load intelligence");setData({configured:false,summary:EMPTY_SUMMARY,conversations:[]})}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const summary=data?.summary||EMPTY_SUMMARY;
 const stats: [LucideIcon,string,string|number][] = [[MessageCircle,"Conversations",summary.total],[AlertTriangle,"Unread",summary.unread],[Clock3,"Avg response",summary.avgResponseMinutes==null?"—":`${summary.avgResponseMinutes}m`],[BrainCircuit,"Inbound / outbound",`${summary.inbound} / ${summary.outbound}`]];
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return (data?.conversations||[]).filter(c=>(filter==="all"||c.sentiment===filter)&&(!q||`${c.name||""} ${c.phone||""} ${c.preview||""}`.toLowerCase().includes(q)))},[data,query,filter]);
 async function runAssist(task:string){if(!selected)return;setAssistLoading(true);setAssistError("");setAssist("");try{const r=await fetch("/api/intelligence/assist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:selected.id,task})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Copilot request failed.");setAssist(d.text||"")}catch(e){setAssistError(e instanceof Error?e.message:"Copilot request failed")}finally{setAssistLoading(false)}}
 async function copyAssist(){if(!assist)return;await navigator.clipboard.writeText(assist);setCopied(true);window.setTimeout(()=>setCopied(false),1400)}
 return <section className="intelligence-hub">
  <div className="intelligence-hero glass"><div className="intelligence-orbit"><span/><span/><BrainCircuit size={38}/></div><div><div className="eyebrow">CONVERSATION INTELLIGENCE</div><h2>Relationship signal, not noise.</h2><p className="muted">Turn real WhatsApp conversations into response, sentiment, and attention signals.</p></div><button className="icon-button" onClick={()=>void load()} title="Refresh"><RefreshCw size={17}/></button></div>
  {error&&<div className="error">{error}</div>}
  <div className="intelligence-stats">{stats.map(([Icon,label,value])=><div className="card glass" key={label}><Icon size={18}/><span className="label">{label}</span><strong>{value}</strong></div>)}</div>
  <div className="intelligence-toolbar glass"><div className="searchbox"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations…"/></div><div className="filter-pills">{["all","positive","neutral","negative"].map(v=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{v}</button>)}</div></div>
  <div className="intelligence-list glass"><div className="panel-head"><div><div className="eyebrow">LIVE SIGNALS</div><h3>Conversation health</h3></div><span className="small muted">{loading?"Analyzing…":`${visible.length} shown`}</span></div>
   {loading?<div className="empty"><strong>Reading workspace conversations…</strong><span>No synthetic data is generated.</span></div>:visible.length===0?<div className="empty"><strong>No matching conversations</strong><span>Connect WhatsApp or adjust the filters.</span></div>:<div className="intelligence-rows">{visible.map(c=><button className="intelligence-row" key={c.id} onClick={()=>{setSelected(c);setAssist("");setAssistError("")}}><div className="signal-dot" data-sentiment={c.sentiment}/><div className="signal-main"><strong>{c.name||c.phone||"Unknown contact"}</strong><span>{c.phone||""}</span><p>{c.preview||"No message preview"}</p></div><div className="signal-metrics"><b className={`sentiment ${c.sentiment}`}>{c.sentiment}</b><span>{c.message_count} messages</span><span>{c.responseMinutes==null?"No response pair":`${c.responseMinutes}m avg response`}</span></div>{c.unread_count>0&&<span className="unread-badge">{c.unread_count}</span>}</button>)}</div>}
  </div>
  {selected&&<div className="intelligence-copilot glass"><div className="copilot-head"><div><div className="eyebrow">AI COPILOT</div><h3>{selected.name||selected.phone||"Conversation"}</h3><span className="muted">Uses the latest real messages from this conversation.</span></div><button className="icon-button" onClick={()=>setSelected(null)} title="Close"><X size={17}/></button></div><div className="copilot-actions"><button onClick={()=>void runAssist("Draft a concise, helpful reply to the latest customer message.")}><Sparkles size={16}/>Draft reply</button><button onClick={()=>void runAssist("Summarize the customer's intent, unresolved issues, and the safest next action in 3 short bullet points.")}><BrainCircuit size={16}/>Summarize</button><button onClick={()=>void runAssist("Identify any complaint, escalation risk, or follow-up obligation in the latest conversation. If none is present, say so briefly.")}><AlertTriangle size={16}/>Risk check</button></div>{assistError&&<div className="error">{assistError}</div>}{assistLoading?<div className="copilot-output"><span className="copilot-pulse"/><span>Copilot is reading the conversation…</span></div>:assist&&<div className="copilot-output"><div>{assist}</div><button className="icon-button" onClick={()=>void copyAssist()} title="Copy result">{copied?<Check size={16}/>:<Copy size={16}/>}</button></div>}<p className="small muted">AI output is advisory. Review it before sending or acting on it.</p></div>}
 </section>
}
