"use client";
import { useEffect, useMemo, useState } from "react";
import { Bot, Check, ChevronDown, Clock3, GitBranch, GripVertical, MessageSquare, Play, Plus, Save, Sparkles, Tag, Trash2, Webhook, Zap } from "lucide-react";

type NodeType="trigger"|"condition"|"action";
type FlowNode={id:string;type:NodeType;label:string;config:Record<string,string>;x:number;y:number};
type Edge={id:string;source:string;target:string};
type Flow={id:string;name:string;enabled:boolean;conditions:{nodes:FlowNode[];edges:Edge[];version:number}};
const palette:Array<{type:NodeType;kind:string;label:string;icon:typeof Zap;config:Record<string,string>}>= [
 {type:"trigger",kind:"message_received",label:"Incoming message",icon:Zap,config:{event:"message_received"}},
 {type:"trigger",kind:"keyword",label:"Keyword trigger",icon:MessageSquare,config:{event:"keyword"}},
 {type:"trigger",kind:"schedule",label:"Schedule trigger",icon:Clock3,config:{event:"schedule"}},
 {type:"trigger",kind:"webhook",label:"Webhook trigger",icon:Webhook,config:{event:"webhook"}},
 {type:"condition",kind:"contains",label:"Message contains",icon:GitBranch,config:{condition:"contains"}},
 {type:"condition",kind:"tag",label:"Contact has tag",icon:Tag,config:{condition:"tag"}},
 {type:"condition",kind:"time",label:"Time / day",icon:Clock3,config:{condition:"time"}},
 {type:"condition",kind:"ai",label:"AI classification",icon:Bot,config:{condition:"ai"}},
 {type:"action",kind:"send",label:"Send message",icon:MessageSquare,config:{action:"send"}},
 {type:"action",kind:"ai_reply",label:"AI reply",icon:Sparkles,config:{action:"ai_reply"}},
 {type:"action",kind:"tag",label:"Add / remove tag",icon:Tag,config:{action:"tag"}},
 {type:"action",kind:"delay",label:"Delay",icon:Clock3,config:{action:"delay"}},
 {type:"action",kind:"webhook",label:"Call webhook",icon:Webhook,config:{action:"webhook"}},
 {type:"action",kind:"stop",label:"Stop flow",icon:Check,config:{action:"stop"}}
];
function starter():FlowNode[]{return [{id:crypto.randomUUID(),type:"trigger",label:"Incoming message",config:{event:"message_received"},x:40,y:110},{id:crypto.randomUUID(),type:"condition",label:"Message contains",config:{condition:"contains",value:"hello"},x:320,y:110},{id:crypto.randomUUID(),type:"action",label:"Send message",config:{action:"send",body:"Thanks for reaching out!"},x:600,y:110}];}
export default function VisualAutomationHub(){
 const [flows,setFlows]=useState<Flow[]>([]),[selected,setSelected]=useState<string>(""),[nodes,setNodes]=useState<FlowNode[]>(starter),[edges,setEdges]=useState<Edge[]>([]),[name,setName]=useState("Welcome flow"),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/visual-automation",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to load flows");setFlows(d.flows||[]);if(d.flows?.[0]){const f=d.flows[0];setSelected(f.id);setName(f.name);setEnabled(f.enabled);setNodes(f.nodes||f.conditions?.nodes||[]);setEdges(f.edges||f.conditions?.edges||[]);}}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const selectedNode=useMemo(()=>nodes.find(n=>n.id===selected),[nodes,selected]);
 function add(item:typeof palette[number]){const id=crypto.randomUUID();const prev=nodes[nodes.length-1];const n:FlowNode={id,type:item.type,label:item.label,config:{...item.config},x:prev?prev.x+280:40,y:prev?.y||110};setNodes(v=>[...v,n]);if(prev)setEdges(v=>[...v,{id:crypto.randomUUID(),source:prev.id,target:id}]);setSelected(id);}
 function updateNode(patch:Partial<FlowNode>&{config?:Record<string,string>}){if(!selectedNode)return;setNodes(v=>v.map(n=>n.id===selectedNode.id?{...n,...patch,config:{...n.config,...patch.config}}:n));}
 function removeNode(){if(!selectedNode)return;setNodes(v=>v.filter(n=>n.id!==selectedNode.id));setEdges(v=>v.filter(e=>e.source!==selectedNode.id&&e.target!==selectedNode.id));setSelected("");}
 async function save(){setBusy(true);setError("");try{const r=await fetch("/api/visual-automation",{method:selected?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(selected?{id:selected,action:"update",name,nodes,edges,enabled,version:flows.find(f=>f.id===selected)?.conditions?.version||1}:{name,nodes,edges,enabled})});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to save flow");setNotice("Flow saved successfully.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save flow.");}finally{setBusy(false);}}
 async function toggle(id:string){const r=await fetch("/api/visual-automation",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action:"toggle"})});const d=await r.json();if(!r.ok)setError(d.error||"Unable to toggle flow");else await load();}
 async function test(){if(!selected)return;const r=await fetch("/api/visual-automation",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:selected,action:"test"})});const d=await r.json();if(!r.ok)setError(d.error||"Test failed");else setNotice(d.run?.result?.message||"Validation complete.");}
 function openFlow(f:Flow){setSelected(f.id);setName(f.name);setEnabled(f.enabled);setNodes(f.conditions?.nodes||[]);setEdges(f.conditions?.edges||[]);}
 return <section className="visual-automation"><div className="va-hero glass"><div className="va-orbit"><div/><div/><Sparkles size={25}/></div><div><div className="eyebrow">PHASE 11 / VISUAL AUTOMATION ENGINE</div><h2>Design automation as a live flow.</h2><p>Triggers, conditions, branches and actions persist server-side and execute through LaaWa's real messaging engine.</p></div><div className="va-health"><span/> ENGINE READY</div></div>
 {notice&&<div className="va-notice"><Check size={15}/>{notice}</div>}{error&&<div className="va-error">{error}</div>}
 <div className="va-toolbar glass"><input value={name} onChange={e=>setName(e.target.value)} aria-label="Flow name"/><span className="va-version">v{flows.find(f=>f.id===selected)?.conditions?.version||1}</span><button onClick={test} disabled={!selected}><Play size={15}/> Test</button><button onClick={save} disabled={busy}><Save size={15}/>{busy?"Saving…":"Save flow"}</button><button className={enabled?"live":""} onClick={()=>selected&&toggle(selected)} disabled={!selected}>{enabled?"LIVE":"DRAFT"}</button></div>
 <div className="va-layout"><aside className="va-palette glass"><div className="va-head"><div><span>NODE LIBRARY</span><strong>Build blocks</strong></div><Plus size={16}/></div>{(["trigger","condition","action"] as NodeType[]).map(type=><div key={type}><small className="va-group">{type.toUpperCase()}</small>{palette.filter(p=>p.type===type).map(p=>{const I=p.icon;return <button key={p.kind} onClick={()=>add(p)} draggable><GripVertical size={13}/><I size={15}/><span>{p.label}</span></button>})}</div>)}</aside>
 <main className="va-canvas glass"><div className="va-grid"/>{edges.map(e=>{const a=nodes.find(n=>n.id===e.source),b=nodes.find(n=>n.id===e.target);if(!a||!b)return null;return <div key={e.id} className="va-edge" style={{left:a.x+215,top:a.y+50,width:Math.max(30,b.x-a.x-210)}}/>})}{nodes.map(n=>{const I=palette.find(p=>p.type===n.type&&((n.type==="trigger"&&p.config.event===n.config.event)||(n.type==="condition"&&p.config.condition===n.config.condition)||(n.type==="action"&&p.config.action===n.config.action)))?.icon||Zap;return <button key={n.id} className={`va-node ${n.type} ${selected===n.id?"selected":""}`} style={{left:n.x,top:n.y}} onClick={()=>setSelected(n.id)}><span className="va-node-icon"><I size={16}/></span><span><small>{n.type.toUpperCase()}</small><strong>{n.label}</strong><em>{n.config.value||n.config.body||n.config.event||n.config.condition||n.config.action||"Configure block"}</em></span></button>})}<div className="va-canvas-hint">Click a node to configure it · Add blocks from the library</div></main>
 <aside className="va-inspector glass"><div className="va-head"><div><span>INSPECTOR</span><strong>{selectedNode?selectedNode.label:"Flow settings"}</strong></div></div>{selectedNode?<><label>Label<input value={selectedNode.label} onChange={e=>updateNode({label:e.target.value})}/></label><label>Configuration<input value={selectedNode.config.value||selectedNode.config.body||""} onChange={e=>updateNode({config:{value:e.target.value,body:e.target.value}})} placeholder={selectedNode.type==="condition"?"Condition value":"Message / configuration"}/></label><label>Node type<select value={selectedNode.type} onChange={e=>updateNode({type:e.target.value as NodeType})}><option value="trigger">Trigger</option><option value="condition">Condition</option><option value="action">Action</option></select></label><button className="va-danger" onClick={removeNode}><Trash2 size={15}/> Remove node</button></>:<div className="va-empty"><GitBranch size={22}/><span>Select a node to edit its configuration.</span></div>}</aside></div>
 <section className="va-flows glass"><div className="va-head"><div><span>SAVED FLOWS</span><strong>Automation control room</strong></div><span>{flows.length} flows</span></div>{!flows.length?<div className="va-empty"><Zap size={22}/><span>No saved flows yet. Build your first flow above.</span></div>:flows.map(f=><article key={f.id} className={selected===f.id?"active":""} onClick={()=>openFlow(f)}><div><strong>{f.name}</strong><span>{f.conditions?.nodes?.length||0} nodes · v{f.conditions?.version||1}</span></div><button onClick={e=>{e.stopPropagation();toggle(f.id)}}>{f.enabled?"LIVE":"DRAFT"}</button><ChevronDown size={16}/></article>)}</section></section>;
}
