"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { BookOpen, Braces, Boxes, Check, Copy, ExternalLink, LockKeyhole, Radio, ShieldCheck, Sparkles } from "lucide-react";
import "../../developer.css";
import "./docs.css";
const groups = [
 { title:"System",items:[["GET","/"],["GET","/health"],["GET","/openapi.json"]] },
 { title:"API Keys",items:[["GET","/keys"],["POST","/keys"],["DELETE","/keys/{id}"]] },
 { title:"Messaging",items:[["GET","/messages"],["POST","/messages"]] },
 { title:"Data",items:[["GET","/conversations"],["GET","/contacts"]] },
 { title:"Realtime",items:[["GET","/events?accountId={accountId}"]] },
 { title:"Operations",items:[["GET","/notifications"],["GET","/metrics"]] },
 { title:"Privacy",items:[["GET","/privacy"],["PATCH","/privacy"],["POST","/privacy"],["GET","/privacy/export"]] },
 { title:"Plugins",items:[["GET","/plugins"],["POST","/plugins"],["PATCH","/plugins/{id}"],["DELETE","/plugins/{id}"],["POST","/plugins/{id}/test"]] },
];
export default function DeveloperDocsPage(){const[copied,setCopied]=useState(false);const[base,setBase]=useState("/api/v1");useEffect(()=>setBase(`${window.location.origin}/api/v1`),[]);const copy=async()=>{await navigator.clipboard?.writeText(`${base}/openapi.json`);setCopied(true);setTimeout(()=>setCopied(false),1600)};return <main className="developer-shell docs-shell"><div className="developer-orb developer-orb-one"/><div className="developer-orb developer-orb-two"/><section className="developer-header docs-header"><div><div className="developer-kicker"><Sparkles size={13}/> LaaWa Developer Platform</div><h1>API Documentation</h1><p>Build on a versioned API with scoped authentication, messaging, realtime events, privacy controls, and external plugins.</p></div><div className="docs-open-actions"><Link className="developer-badge docs-open" href="/developer/plugins"><Boxes size={15}/> Plugin Center</Link><a className="developer-badge docs-open" href="/api/v1/openapi.json" target="_blank" rel="noreferrer"><ExternalLink size={15}/> OpenAPI</a></div></section><section className="docs-layout"><aside className="developer-card docs-sidebar"><div className="docs-sidebar-title"><BookOpen size={18}/> Reference</div>{groups.map(group=><div className="docs-group" key={group.title}><span>{group.title}</span>{group.items.map(([method,path])=><div className="docs-nav-item" key={`${method}-${path}`}><b className={`docs-method docs-${method.toLowerCase()}`}>{method}</b><code>{path}</code></div>)}</div>)}</aside><div className="docs-main"><article className="developer-card docs-hero-card"><div className="docs-icon"><Braces size={22}/></div><div><h2>One contract. Every extension.</h2><p>OpenAPI 3.0 is available directly from this deployment. Plugins receive signed HTTPS events and operate outside the Next.js runtime.</p></div></article><div className="docs-grid"><article className="developer-card docs-feature"><ShieldCheck size={20}/><h3>Scoped permissions</h3><p>Grant only the data capabilities and event types each plugin needs.</p></article><article className="developer-card docs-feature"><Radio size={20}/><h3>Signed realtime events</h3><p>Each plugin delivery carries an HMAC-SHA256 signature for verification.</p></article><article className="developer-card docs-feature"><Check size={20}/><h3>Deploy anywhere</h3><p>The plugin gateway uses standard HTTPS and stays compatible with Vercel and Netlify.</p></article></div><article className="developer-card docs-endpoint-card"><div className="developer-card-title"><span className="developer-icon"><Braces size={19}/></span><div><h2>OpenAPI endpoint</h2><p>Machine-readable contract for tooling and client generation.</p></div></div><div className="docs-copy-row"><code>{base}/openapi.json</code><button className="developer-primary docs-copy" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?"Copied":"Copy"}</button></div></article></div></section></main>}
