"use client";

import Link from "next/link";
import { Activity, Boxes, Check, ChevronRight, ExternalLink, FlaskConical, KeyRound, Link2, LockKeyhole, PackagePlus, RefreshCw, ShieldCheck, Sparkles, Trash2, Webhook, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import "../../developer.css";
import "./plugins.css";

const PERMISSIONS = ["messages.read", "messages.write", "contacts.read", "conversations.read", "broadcasts.read", "accounts.read"] as const;
const EVENTS = ["message.received", "message.sent", "conversation.created", "conversation.updated", "contact.created", "contact.updated", "broadcast.completed", "broadcast.failed", "whatsapp.connected", "whatsapp.disconnected", "webhook.failed"] as const;
type Plugin = { id:string; slug:string; name:string; version:string; description:string; author:string; homepageUrl:string|null; enabled:boolean; installed:boolean; installationId:string|null; installationEnabled:boolean|null; events:string[]; permissions:string[]; lastDeliveredAt:string|null; lastError:string|null };
type Created = { pluginId:string; slug:string; name:string; version:string; secret:string };

export default function PluginsPage(){
 const [plugins,setPlugins]=useState<Plugin[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[open,setOpen]=useState(false),[created,setCreated]=useState<Created|null>(null);
 const [form,setForm]=useState({slug:"",name:"",version:"1.0.0",description:"",author:"",callbackUrl:"",permissions:["messages.read"],events:["message.received"]});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/v1/plugins",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Unable to load plugins.");setPlugins(b.data||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load plugins.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const installed=useMemo(()=>plugins.filter(p=>p.installed),[plugins]);
 function toggle(list:string[],value:string){return list.includes(value)?list.filter(v=>v!==value):[...list,value]}
 async function install(){setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/v1/plugins",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({manifest:form})}),b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Unable to install plugin.");setCreated(b.data);setOpen(false);setNotice("Plugin installed. Save the generated signing secret in the plugin securely — it will not be shown again.");setForm({slug:"",name:"",version:"1.0.0",description:"",author:"",callbackUrl:"",permissions:["messages.read"],events:["message.received"]});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to install plugin")}finally{setBusy(false)}}
 async function patch(id:string,input:Record<string,unknown>){setBusy(true);setError("");try{const r=await fetch(`/api/v1/plugins/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)}),b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Unable to update plugin.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update plugin")}finally{setBusy(false)}}
 async function test(id:string){setBusy(true);setError("");setNotice("");try{const r=await fetch(`/api/v1/plugins/${id}/test`,{method:"POST"}),b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Test delivery failed.");setNotice(`${b.data.deliveries} plugin test delivery${b.data.deliveries===1?"":"ies"} dispatched.`);await load()}catch(e){setError(e instanceof Error?e.message:"Plugin test failed")}finally{setBusy(false)}}
 async function remove(id:string){if(!window.confirm("Uninstall this plugin from the workspace?"))return;setBusy(true);setError("");try{const r=await fetch(`/api/v1/plugins/${id}`,{method:"DELETE"}),b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Unable to uninstall plugin.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to uninstall plugin")}finally{setBusy(false)}}
 return <main className="developer-shell plugins-shell"><div className="developer-orb developer-orb-one"/><div className="developer-orb developer-orb-two"/><div className="plugins-starfield"/>
  <section className="developer-header plugins-hero"><div><div className="developer-kicker"><Sparkles size={13}/> LaaWa Extension Platform</div><h1>Plugin Control Center</h1><p>Extend LaaWa through signed, permission-scoped HTTPS plugins without executing untrusted plugin code inside the web runtime.</p></div><div className="plugins-hero-badge"><span><Boxes size={18}/></span><div><strong>{installed.length} installed</strong><small>secure extensions</small></div></div></section>
  <nav className="developer-quicknav"><Link href="/developer/docs">API Docs</Link><Link href="/developer/engines">Engines</Link><Link href="/developer/sdk">SDKs</Link><Link href="/developer/n8n">n8n</Link><Link href="/developer/integrations"><Link2 size={14}/> Integrations</Link><Link href="/developer/notifications">Notifications</Link><Link href="/developer/observability">Observability</Link><Link href="/developer/privacy"><LockKeyhole size={14}/> Privacy</Link><Link className="active" href="/developer/plugins"><Boxes size={14}/> Plugins</Link></nav>
  {error&&<div className="developer-error plugin-alert"><X size={16}/>{error}</div>}{notice&&<div className="plugin-notice"><ShieldCheck size={16}/>{notice}</div>}
  <section className="plugin-top-grid"><article className="developer-card plugin-principles"><div className="plugin-card-title"><span className="developer-icon"><ShieldCheck size={19}/></span><div><h2>Secure by design</h2><p>Plugins are external HTTPS services. LaaWa only stores their manifest, encrypted secret, settings and event subscription.</p></div></div><div className="principle-grid"><Principle icon={<KeyRound size={15}/>} title="Signed events" text="HMAC-SHA256 delivery signatures"/><Principle icon={<LockKeyhole size={15}/>} title="Scoped access" text="Explicit permissions per install"/><Principle icon={<Webhook size={15}/>} title="HTTPS only" text="No local/private callback targets"/><Principle icon={<Activity size={15}/>} title="Delivery health" text="Attempts and failures tracked"/></div></article><article className="developer-card plugin-install-card"><div className="plugin-card-title"><span className="developer-icon"><PackagePlus size={19}/></span><div><h2>Install an extension</h2><p>Connect a plugin endpoint using its manifest.</p></div></div><button className="developer-primary" onClick={()=>setOpen(true)}><PackagePlus size={16}/> Add plugin</button><div className="plugin-install-hint"><span className="plugin-dot"/>No plugin code is bundled into Next.js. Web/API stays Vercel &amp; Netlify friendly.</div></article></section>
  <section className="plugin-section-head"><div><div className="developer-kicker"><Boxes size={13}/> Workspace extensions</div><h2>Installed plugins</h2></div><button className="plugin-refresh" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?"plugin-spin":""} size={15}/></button></section>
  {loading?<div className="plugin-empty developer-card shimmer">Loading extension registry…</div>:installed.length===0?<div className="plugin-empty developer-card"><div className="plugin-empty-orb"><Boxes size={25}/></div><h3>Your extension layer is empty</h3><p>Install your first external plugin to receive signed LaaWa events.</p><button className="developer-primary" onClick={()=>setOpen(true)}><PackagePlus size={16}/> Install plugin</button></div>:<section className="plugin-list">{installed.map(plugin=><article className="developer-card plugin-card" key={plugin.id}><div className="plugin-card-head"><div className="plugin-avatar"><Boxes size={21}/></div><div className="plugin-name"><h3>{plugin.name}</h3><span>{plugin.slug} · v{plugin.version}</span></div><span className={`plugin-status ${plugin.installationEnabled?"on":"off"}`}><i/>{plugin.installationEnabled?"Enabled":"Disabled"}</span></div><p className="plugin-description">{plugin.description||"External LaaWa extension"}{plugin.author&&<span> · by {plugin.author}</span>}</p><div className="plugin-meta"><div><small>Permissions</small><strong>{plugin.permissions.length||0}</strong></div><div><small>Events</small><strong>{plugin.events.length||0}</strong></div><div><small>Last delivery</small><strong>{plugin.lastDeliveredAt?new Date(plugin.lastDeliveredAt).toLocaleString():"Never"}</strong></div><div><small>Failures</small><strong className={plugin.lastError?"bad":""}>{plugin.lastError?"Attention":"0"}</strong></div></div>{plugin.lastError&&<div className="plugin-error-line"><Activity size={14}/>{plugin.lastError}</div>}<div className="plugin-events"><span>Subscribed:</span>{plugin.events.slice(0,5).map(event=><code key={event}>{event}</code>)}{plugin.events.length>5&&<em>+{plugin.events.length-5}</em>}</div><div className="plugin-actions"><button className="plugin-secondary" disabled={busy} onClick={()=>void patch(plugin.installationId!,{enabled:!plugin.installationEnabled})}>{plugin.installationEnabled?"Disable":"Enable"}</button><button className="plugin-secondary" disabled={busy} onClick={()=>void test(plugin.installationId!)}><FlaskConical size={14}/> Test event</button>{plugin.homepageUrl&&<a className="plugin-secondary" href={plugin.homepageUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Website</a>}<button className="plugin-danger" disabled={busy} onClick={()=>void remove(plugin.installationId!)}><Trash2 size={14}/> Uninstall</button></div></article>)}</section>}
  {open&&<div className="plugin-modal-backdrop"><div className="plugin-modal"><button className="plugin-modal-close" onClick={()=>setOpen(false)}><X size={17}/></button><div className="plugin-modal-mark"><Boxes size={22}/></div><div className="developer-kicker">New extension</div><h2>Connect a plugin</h2><p>The callback receives only the events and permissions you explicitly grant. Generate and store the signing secret after installation.</p><div className="plugin-form"><Field label="Plugin slug"><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="crm-sync" maxLength={64}/></Field><div className="plugin-two"><Field label="Name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="CRM Sync" maxLength={100}/></Field><Field label="Version"><input value={form.version} onChange={e=>setForm({...form,version:e.target.value})} placeholder="1.0.0" maxLength={50}/></Field></div><Field label="Callback URL"><input value={form.callbackUrl} onChange={e=>setForm({...form,callbackUrl:e.target.value})} placeholder="https://plugin.example.com/events" inputMode="url"/></Field><Field label="Description"><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What this extension does…" maxLength={500}/></Field><Field label="Author"><input value={form.author} onChange={e=>setForm({...form,author:e.target.value})} placeholder="Your team" maxLength={100}/></Field><div className="plugin-select-block"><span>Permissions</span><div>{PERMISSIONS.map(item=><button type="button" key={item} className={form.permissions.includes(item)?"selected":""} onClick={()=>setForm({...form,permissions:toggle(form.permissions,item)})}>{form.permissions.includes(item)&&<Check size={12}/>} {item}</button>)}</div></div><div className="plugin-select-block"><span>Events</span><div>{EVENTS.map(item=><button type="button" key={item} className={form.events.includes(item)?"selected":""} onClick={()=>setForm({...form,events:toggle(form.events,item)})}>{form.events.includes(item)&&<Check size={12}/>} {item}</button>)}</div></div></div><div className="plugin-modal-actions"><button className="plugin-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="developer-primary" disabled={busy||!form.slug||!form.name||!form.version||!form.callbackUrl||!form.events.length} onClick={()=>void install()}>{busy?<><RefreshCw className="plugin-spin" size={15}/> Installing…</>:<><PackagePlus size={15}/> Install plugin</>}</button></div></div></div>}
  {created&&<div className="plugin-modal-backdrop"><div className="plugin-secret"><div className="plugin-secret-mark"><ShieldCheck size={24}/></div><div className="developer-kicker">Installation complete</div><h2>Save your signing secret</h2><p>This secret is required by your plugin to verify LaaWa event signatures. It is generated once and never returned by the registry again.</p><div className="plugin-secret-box"><code>{created.secret}</code></div><button className="developer-primary" onClick={()=>setCreated(null)}>I saved it securely <ChevronRight size={15}/></button></div></div>}
 </main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="plugin-field"><span>{label}</span>{children}</label>}
function Principle({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="plugin-principle"><span>{icon}</span><div><strong>{title}</strong><small>{text}</small></div></div>}
